name: CI
on:
  workflow_dispatch:

jobs:
  transform-test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - id: git-config
        shell: bash
        run: |
          git ls-remote https://github.com/ferdle-org/test-branch -q >/dev/null
